services:
 mongo-persons:
  image: mongo:latest
  command: mongod --port 27018
  ports:
    - 27018:27018
  volumes:
    - mongodb_person_data:/data/db

 mongo-dogs:
  image: mongo:latest
  command: mongod --port 27019
  ports:
    - 27019:27019
  volumes:
    - mongodb_dog_data:/data/db

 mongo-competitions:
  image: mongo:latest
  command: mongod --port 27017
  ports:
    - 27017:27017
  volumes:
    - mongodb_competition_data:/data/db
    
 mysql-history:
  image: mysql:latest
  ports:
    - 3306:3306
  volumes:
    - mysql_history_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123
    
 person-service:
  depends_on:
    - mongo-persons
  image: nelet/person-service
  ports:
    - 8080:8080
  links:
    - mongo-persons
  environment:
   MONGODB_PORT: 27018
   MONGODB_HOST: mongo-persons
   SPRING_DATA_MONGODB_URI: mongodb://mongo-persons:27018/person-service
   SERVER_PORT: 8080

 dog-service:
  depends_on:
    - mongo-dogs
  image: nelet/dog-service
  ports:
    - 8084:8084
  links:
    - mongo-dogs
  environment:
   MONGODB_PORT: 27019
   MONGODB_HOST: mongo-dogs
   SPRING_DATA_MONGODB_URI: mongodb://mongo-dogs:27019/dog-service
   SERVER_PORT: 8084
   SPRING_APPLICATION_NAME: dog-service

 competition-service:
  depends_on:
    - mongo-competitions
  image: nelet/competition-service
  ports:
    - 8082:8082
  links:
    - mongo-competitions
  environment:
   MONGODB_PORT: 27017
   MONGODB_HOST: mongo-competitions
   SPRING_DATA_MONGODB_URI: mongodb://mongo-competitions:27017/competition-service
   SERVER_PORT: 8082
   
 history-service:
  depends_on:
    - person-service
    - dog-service
    - competition-service
  image: nelet/history-service
  ports:
    - 8081:8081
  links:
    - person-service
    - dog-service
    - competition-service
  environment:
   PERSON_SERVICE_BASEURL: person-service:8080
   DOG_SERVICE_BASEURL: dog-service:8084
   COMPETITION_SERVICE_BASEURL: competition-service:8082
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-history
   MYSQL_DB_PORT: 3306
   SPRING_DATASOURCE_URL: jdbc:mysql://mysql-history:3306/historydb?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
   SERVER_PORT: 8081

volumes:
 mongodb_person_data:
 mongodb_dog_data:
 mongodb_competition_data:
 mysql_history_data:
 